### ISSUE TITLE
Error when publishing to influx DB

### ISSUE THREAD

**Issue by eBoon123** [vinceskahan/wfudptools#6]
First off - thank you for the tool. I am coming from the old deprecated repo.

I'm getting the following error when testing with my influxdb:

>wfudplistener --influxdb --influxdb_host=192.168.1.105 --influxdb_port=8086  --influxdb_db=weatherflow -M -n

setting up socket - done
listening for broadcasts..
Failed to connect to InfluxDB: name 'args' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 537, in influxdb_publish
    client = InfluxDBClient(host=args.influxdb_host,
NameError: name 'args' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wfudplistener", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 746, in main
    elif data["type"] == "rapid_wind":    process_rapid_wind(data,args)
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 227, in process_rapid_wind
    influxdb_publish(topic, rapid_wind)
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 556, in influxdb_publish
    print("  Payload was: %s" % payload)
UnboundLocalError: local variable 'payload' referenced before assignment
root@WeatherFlowInflux:~# wfudplistener --influxdb --influxdb_host=192.168.1.105 --influxdb_port=8086  --influxdb_db=weatherflow -M -n -v
setting up socket - done
listening for broadcasts..
Failed to connect to InfluxDB: name 'args' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 537, in influxdb_publish
    client = InfluxDBClient(host=args.influxdb_host,
NameError: name 'args' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wfudplistener", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 751, in main
    elif data["type"] == "hub_status":    process_hub_status(data,args)
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 527, in process_hub_status
    influxdb_publish(topic, hub_status)     # careful here, might need to hub_status.pop("foo", None) for arrays
  File "/usr/local/lib/python3.9/dist-packages/wfudptools/listener.py", line 556, in influxdb_publish
    print("  Payload was: %s" % payload)
UnboundLocalError: local variable 'payload' referenced before assignment

Thank you for any insights you can provide!

**Comment by krispayne** [comment]
What version of InfluxDB are you using? It looks like this tool is set up for InfluxDB v1, not v2. I'm looking at the code now to see how quick it would be to port it to v2.

**Comment by vinceskahan** [comment]
guys - see if the develop branch helps any.  I merged a PR related to v2 last year but maybe neglected to merge it up to main.  It's been so long I can't remember any more...

**Comment by krispayne** [comment]
@vinceskahan oh perfect, somehow I missed that branch. Works like a charm.

**Comment by vinceskahan** [comment]
leaving this open until I get around to merging up to main....

**Comment by eBoon123** [comment]
> guys - see if the develop branch helps any. I merged a PR related to v2 last year but maybe neglected to merge it up to main. It's been so long I can't remember any more...

Dumb question ... how do I install from the development branch?

**Comment by vinceskahan** [comment]
Download from [here](https://raw.githubusercontent.com/vinceskahan/wfudptools/develop/wfudptools/listener.py) and use that to overwrite your listener.py file wherever you installed it to on your system.   If there is a listener pyc in the same tree on your system, you'd want to delete that too.

Mine within a venv for this tool is located as follows:
````
./lib/python3.11/site-packages/wfudptools/__pycache__/listener.cpython-311.pyc
./lib/python3.11/site-packages/wfudptools/listener.py

````

Your location might vary a little but there should be two files.  One listener.py (the source) and one .pyc file (the compiled version).  Delete the .pyc file and overwrite the .py file with the updated one.  Should work.

If you mess it up somehow, you can always 'pip install' again to go back to where you started.

**Comment by vinceskahan** [comment]
If one of you guys could test the new 5.3.0 from https://test.pypi.org/project/wfudptools/ and let me know if it's looking ok, it would be much appreciated.  I can push a new one up to the production pypi after one of you confirm the influxdb v2 stuff is working in the new version.

(and thanks for reminding me I'd forgotten to merge to main last summer....)

**Comment by eBoon123** [comment]
> Download from [here](https://raw.githubusercontent.com/vinceskahan/wfudptools/develop/wfudptools/listener.py) and use that to overwrite your listener.py file wherever you installed it to on your system. If there is a listener pyc in the same tree on your system, you'd want to delete that too.
> 
> Mine within a venv for this tool is located as follows:
> 
> ```
> ./lib/python3.11/site-packages/wfudptools/__pycache__/listener.cpython-311.pyc
> ./lib/python3.11/site-packages/wfudptools/listener.py
> ```
> 
> Your location might vary a little but there should be two files. One listener.py (the source) and one .pyc file (the compiled version). Delete the .pyc file and overwrite the .py file with the updated one. Should work.
> 
> If you mess it up somehow, you can always 'pip install' again to go back to where you started.

This absolutely fixed my issue - working perfectly now!

**Comment by eBoon123** [comment]
> If one of you guys could test the new 5.3.0 from https://test.pypi.org/project/wfudptools/ and let me know if it's looking ok, it would be much appreciated. I can push a new one up to the production pypi after one of you confirm the influxdb v2 stuff is working in the new version.
> 
> (and thanks for reminding me I'd forgotten to merge to main last summer....)
> 
> To try it ....
> 
> ```
> pip3 install --upgrade -i https://test.pypi.org/simple/wfudptools==5.3.0 
> ```

Quick test:

`root@WeatherFlowUDPTools:~# pip3 install --upgrade -i https://test.pypi.org/simple/wfudptools==5.3.0 
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.`

I'm missing something simple I think ..... (sorry)

**Comment by vinceskahan** [comment]
yes, the python folks and debian especially screwed all their users with this change.

cd
python -m venv wfudptools-venv
source wfudptools-venv/bin/activate
pip install <modulehere>

Then the module will be installed within the python virtual environment.  You need to either activate the venv via the 'source' command above or dig down into that tree and find the listen.py file buried way down in there and call it with an absolute pathname.

grrrrrr.....python and debian rigid zealots.....

**Comment by vinceskahan** [comment]
closing

**Comment by eBoon123** [comment]
> yes, the python folks and debian especially screwed all their users with this change.
> 
> cd python -m venv wfudptools-venv source wfudptools-venv/bin/activate pip install
> 
> Then the module will be installed within the python virtual environment. You need to either activate the venv via the 'source' command above or dig down into that tree and find the listen.py file buried way down in there and call it with an absolute pathname.
> 
> grrrrrr.....python and debian rigid zealots.....

I ended up just nuking the venv

1.  Created a LXC Container based off of Debian 12
2.  rm /usr/lib/python3.11/EXTERNALLY-MANAGED
3. apt install pip
4. pip3 install wfudptools
5. added @reboot nohup  /usr/local/bin/wfudplistener --influxdb --influxdb_host=192.168.1.105 --influxdb_port=8086 --influxdb_db=weatherflow -M &

everything worked perfectly.

Thank you for your help and this awesome project!
